### ISSUE TITLE
Create new account plugin

### ISSUE THREAD

**Issue by zASSAz** [candy-chat/candy-plugins#100]
It will be fine to have new user registration plugin in chat. Something like "Register" button on login form.

**Comment by manasb** [comment]
I think this would be a good plugin to have. For help & tips, converse.js has code for registering an account.

**Comment by singpolyma** [comment]
I have a basic plugin implementing this working locally

**Comment by gibus** [comment]
@singpolyma hello, I'm currently facing the same need and I'd be interested by your implementation (in order to not rewrite the wheel). It would be very kind if you can post it. Thx!

**Comment by gibus** [comment]
I think this issue can be close with #167
