### ISSUE TITLE
Hashtag feeds

### ISSUE THREAD

**Issue by Chronos6** [candy-chat/candy-plugins#132]
Hi,

A nice feature would be to have pseudo rooms, where messages are listed in chronological order what include a certain hashtag. To such a hashtag feed rooms could be added in order to aggregate information. 

The use case I got the idea from is a ~100 head organization where information channeling is really a problem and we are using email as a fallback as chatrooms are not giving enough structure. Email is inefficient, chat is cool.

Cheers,
David

**Comment by mweibel** [comment]
This is a feature which would include doing some kind of server side implementation and therefore I don't think this fits to this repository.
