### ISSUE TITLE
me-does  plug-in does not operate as expected once inline-images is enabled

### ISSUE THREAD

**Issue by vasecthomas** [candy-chat/candy-plugins#133]
me-does operates normally until I enable inline-images.
After doing so, when one invokes a /me command, it operates normally but also outputs an _additional_ line containing just /me
![screenshot - 05052015 - 06 05 11 pm](https://cloud.githubusercontent.com/assets/4716955/7485899/712ddac4-f351-11e4-9449-2e845d59c1b0.png)

**Comment by Sudrien** [comment]
Hmm... first thought, both plugins make use of the candy:view.message.before-show event.

* Which order are each plugins' init() functions called?
* have you set enableXHTML to true in the view options?

**Comment by vasecthomas** [comment]
* I had me-does called out before inline-images. I switched them around and now it works.
* I do not have enableXHTML enabled in the view options. 

Is enabling XHTML required for the <strong> tag to work in the infoMessage? If so, it doesn't seem to work for me like that. 

![screenshot - 05062015 - 05 44 14 am](https://cloud.githubusercontent.com/assets/4716955/7493141/041ca476-f3b3-11e4-9d2e-fc97e663d52f.png)

Did I enable XHTML wrong? 

```javascript
view: { assets: './res/',
	   enableXHTML: true }
```

**Comment by Sudrien** [comment]
No, that's the correct way to set the flag - the tags should be stripped out otherwise. 

The Emphasis plugin can be used to handle formatting. If that's already being used, there may be another load order issue.
