### ISSUE TITLE
Notifications - closetime option on Chrome 47+

### ISSUE THREAD

**Issue by diriver63** [candy-chat/candy-plugins#152]
Closetime = 0 option to keep notifications visible at all times is no longer working on chrome 47+ as google changed the behavior of how notifications interact on Desktop. They require a new flag to explicitly indicate that the notifications should stay visible past 20 seconds. Flag name is 'requireInteraction' and it's type boolean.

Closetime between 1000 and 20000 works as expected. I didn't get to test Closetime > 20000.
For Closetime = 0 to work in my environment with Chrome 47, I made the following changes in candy.js. 

var _options = {
    notifyNormalMessage: true,
    notifyPersonalMessage: true,
    notifyMention: true,
    closeTime: 3000,
    title: null,
    requireInteraction: true, /******** added line ********/
    icon: window.location.origin + '/' + Candy.View.getOptions().assets + '/img/favicon.png'
  };

and on function handleOnShow:

// Create the notification.
        var title = !_options.title ? args.name : _options.title ,
          notification = new window.Notification(title, {
          icon: _options.icon,
          body: args.message,
          requireInteraction: _options.requireInteraction /******** added line ********/
        });

**Comment by maennchen** [comment]
Thank you very much @diriver63.

Could you possibly make a pull request for that change?

**Comment by diriver63** [comment]
Sure.. I just created one

**Comment by maennchen** [comment]
Fixed by #153

Thank you @diriver63!
