### ISSUE TITLE
inline-videos plugin enables XSS attack

### ISSUE THREAD

**Issue by smokku** [candy-chat/candy-plugins#156]
After enabling `inline-videos` plugin, Candy inserts HTML embedded in message body as HTML, not text - this allows sending all kind of HTML tags, especially `<script>` tag is interesting.

Repro:
- Load and init() `inline-images` plugin.
- Send the following message to yourself:
```html
<script type="text/javascript">alert('Boo!')</script>
```

**Comment by Sudrien** [comment]
Confirmed for `inline-videos`. Did not test for `inline-images`, as that is not my code.

I think it may be the 

> jQuery.parseHTML(args.message)

doing it. This is going to be annoying.

**Comment by smokku** [comment]
inline-images is ok. This is specific to inline-videos.

**Comment by mweibel** [comment]
@Sudrien do you remember why the jQuery.parseHTML is used there?

**Comment by Sudrien** [comment]
@mweibel  jQuery.parseHTML was an 'efficient' way to get a DOM object out of the string. 

a.hostname
a.pathname
a.path

Are from the browser url parsing (An <a> element), and make regexs manageable.

Note: jQuery.parseHTML has a keepScripts option, but that obviously has no effect in this case.

**Comment by Sudrien** [comment]
Ok, testing brought up more issues than the XSS vulnerability, So I wen ahead and fixed them too. 

Result of given test case is now
```html
alert('Boo!')
```
in the case of an args.xhtmlMessage ...that is, tag is stripped. As args.xhtmlMessage was not supported before, this is an enhancement. 

```html
<script type="text/javascript">alert('Boo!')</script>
```

...is what shows up in a standard args.message - safe behavior, if not the most consistent.


Also, replacing jQuery.parseHTML with a link-detecting regex means multiple video handling is better.

@smokku , @mweibel - Any comments on the code before I merge with master?

**Comment by smokku** [comment]
This is how XHTML-IM (and HTML) is supposed to work, by stripping and not parsing unknown tags, leaving CDATA alone. If the sender intended these tags to be text, one should use `&lt;` entity instead of `<` char.

The code and effect looks fine to me. :+1:

**Comment by Sudrien** [comment]
5e8b504 addresses @smokku & @mweibel's comments.
