### ISSUE TITLE
notifyme must be initialized before medoes for the latter to work

### ISSUE THREAD

**Issue by ge0rg** [candy-chat/candy-plugins#160]
When using both plugins, MeDoes does not properly work if it is initialized before NotifyMe. This order works:

                        CandyShop.NotifyMe.init();
                        CandyShop.MeDoes.init();

**Comment by Sudrien** [comment]
Thank you - this behavior is already noted at the end of the README, though.

https://github.com/candy-chat/candy-plugins/blob/ce0e518587db2b6315d4d08b4c96d2f4fcab8518/me-does/README.md

Unfortunately I see no easy fix while me-does remains a plugin - it's a hack.

I'd be happy to consider any suggestions in updating documentiaon, @ge0rg.

**Comment by ge0rg** [comment]
Oh, thanks for pointing out. I stopped reading the documentation at the installation instructions. Probably the addition of a simple "at the end of the initialization section, after all other modules" statement before the Javascript fragment would have prevented my confusion.
