### ISSUE TITLE
AvailableRooms does not appear

### ISSUE THREAD

**Issue by vystepanenko** [candy-chat/candy-plugins#184]
Maybe someone still alive hre :)

I have problem with AvailableRooms. 
I added script to my index.html
`<script type="text/javascript" src="candy-plugins-master/available-rooms/candy.js"></script>`

Then add init method 
` CandyShop.AvailableRooms.init();`
But have no tab with available rooms.
Maybe I must do something else?

ps. For example Join plugin works fine

**Comment by kousu** [comment]
I ran into this too, and I've fixed it.
